<?php

/**
 * Implements hook_migrate_api()
 */
function library_migrate_migrate_api() {
  $api = array(
      'api' => 2,
      'migrations' => array(
          'FileCollection' => array('class_name' => 'FileCollectionMigration'),
          'FileFolder' => array('class_name' => 'FileFolderMigration'),
          'FileCategory' => array('class_name' => 'FileCategoryMigration'),
          'Files' => array('class_name' => 'FilesMigration'),
          'People' => array('class_name' => 'PeopleMigration'),
          'Location' => array('class_name' => 'LocationMigration'),
          'Events' => array('class_name' => 'EventsMigration'),
          'Topics' => array('class_name' => 'TopicsMigration'),
      ),
  );
  return $api;
}


