<?php

/**
 * Deleting information about field from information structure
 *
 * @param $field
 * @param $bundle
 * @param $facet_filters_settings
 * @param $filter
 */
function filters_ui_fivestar_delete_field($field, $bundle, &$facet_filters_settings, $filter)
{
    if ($filter['state'] == 'visible') {
        $tag = $field['settings']['axis'];
        if (array_key_exists($bundle, $facet_filters_settings[$field['type']][$tag])) {
            unset($facet_filters_settings[$field['type']][$tag][$bundle]);
        }
    }
}

/**
 * Add information about field to information structure
 *
 * @param $field
 * @param $bundle
 * @param $facet_filters_settings
 * @param $filter
 */
function filters_ui_fivestar_add_field($field, $bundle, &$facet_filters_settings, $filter)
{
    if ($filter['state'] == 'visible') {
        $tag = $field['settings']['axis'];
        if (!isset($facet_filters_settings[$field['type']][$tag])) {
            $facet_filters_settings[$field['type']][$tag] = array();
        }
        $facet_filters_settings[$field['type']][$tag][$bundle] = array();
    }
}

/**
 * Return information by what current field would be filtered
 *
 * @param $field
 * @return string
 */
function filters_ui_fivestar_filter_by($field)
{
    $filter_by_label = $field['settings']['axis'];
    return 'Voting tag ' . $filter_by_label;
}

/**
 * Implements hook_field_update_field().
 *
 * @param $field
 * @param $prior_field
 * @param $has_data
 */
function filters_ui_fivestar_field_update_field($field, $prior_field, $has_data)
{
    if ($field['type'] == 'fivestar') {
        $facet_filters_settings = drupal_json_decode(variable_get('facet_collection_filters_settings'));
        //Update information about current field in existing version of facet_collections_filters_settings common variable
        if ($field['settings']['axis'] != $prior_field['settings']['axis']) {
            $facet_filters = drupal_json_decode(variable_get('facet_collection_filters'));
            foreach ($facet_filters as $bundle_name => $filters) {
                if (array_key_exists($field['field_name'], $filters) && $filters[$field['field_name']]['state'] == 'visible') {
                    unset($facet_filters_settings[$prior_field['type']][$prior_field['settings']['axis']][$bundle_name]);
                    $facet_filters_settings[$field['type']][$field['settings']['axis']][$bundle_name] = array();
                }
            }
            variable_set('facet_collection_filters_settings', drupal_json_encode($facet_filters_settings));
        }
    }
}