<?php
/**
 * Deleting information about field from information structure
 *
 * @param $field
 * @param $bundle
 * @param $facet_filters_settings
 * @param $filter
 */
function filters_ui_datetime_delete_field($field, $bundle, &$facet_filters_settings, $filter)
{
    if (array_key_exists($bundle, $facet_filters_settings[$field['type']])) {
        unset($facet_filters_settings[$field['type']][$bundle]);
    }
}

/**
 * Add information about field to information structure
 *
 * @param $field
 * @param $bundle
 * @param $facet_filters_settings
 * @param $filter
 */
function filters_ui_datetime_add_field($field, $bundle, &$facet_filters_settings, $filter)
{
    if ($filter['state'] == 'visible') {
        if (!isset($facet_filters_settings[$field['type']])) {
            $facet_filters_settings[$field['type']] = array();
        }
        $facet_filters_settings[$field['type']][$bundle] = array();
    }
}