<?php

/**
 * Implements hook_uninstall().
 */
function filters_ui_datetime_uninstall()
{
    $facet_filters_settings = drupal_json_decode(variable_get('facet_collection_filters_settings'));
    if (isset($facet_filters_settings['datetime'])) {
        unset($facet_filters_settings['datetime']);
        variable_set('facet_collection_filters_settings', drupal_json_encode($facet_filters_settings));
    }
}