<?php

/**
 * Implements hook_menu().
 */
function library_admin_menu() {
  $items = array();
  $items['admin/library_settings'] = array(
    'title' => t('Site configuration page'),
    'dascription' => 'This page is contain all settings for site',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('library_admin_settings_form'),
    'access callback' => TRUE,
    'file' => 'library_admin.settings.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
