<?php

define('LIBRARY_ADMIN_TEXT_TO_COPIRIGHT', variable_get('library_admin_text_to_copyright'));
define('LIBRARY_ADMIN_PATH_TO_COPIRIGHT', variable_get('library_admin_path_to_copyright'));

/**
 * Implements hook_menu().
 */
function library_admin_menu() {
  $items = array();
  $items['admin/library_settings'] = array(
    'title' => t('Site configuration page'),
    'dascription' => t('This page is contain all settings for site'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('library_admin_settings_form'),
    'access callback' => TRUE,
    'file' => 'library_admin.settings.inc',
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function library_admin_ctools_plugin_directory($module, $plugin) {
  if (in_array($module, array('ctools', 'panels'))) {
    return "plugins/$plugin";
  }
}

/**
 * Help function for copiright link.
 */
function library_admin_return_copiright() {
  if ($text = LIBRARY_ADMIN_TEXT_TO_COPIRIGHT && $path = LIBRARY_ADMIN_PATH_TO_COPIRIGHT) {
    $copiright = l(
      t(LIBRARY_ADMIN_TEXT_TO_COPIRIGHT),
      check_url(LIBRARY_ADMIN_PATH_TO_COPIRIGHT)
    );
   return $copiright;
  }
}

/**
 * Form for search by faq page.
 */
function library_admin_faq_form($form, $form_state) {
  $form['main_title'] = array(
    '#prefix' => '<h2>',
    '#markup' => t('Answers'),
    '#suffix' => '</h2>',
  );

  $form['description'] = array(
    '#markup' => t('Find answers to the most commonly asked questions by browsing through our list of topics, or via our search functionality:'),
  );

  $form['title'] = array(
    '#prefix' => '<h3>',
    '#markup' => t('Search'),
    '#suffix' => '</h3хоро>',
  );

  $form['text'] = array(
    '#type' => 'textfield'
  );

  $form['button'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#attributes' => array(
      'class' => array('search-faq')
    )
  );

  return $form;
}
