<?php

/*
 * Implements hook_block_info()
 */
function facet_collection_search_block_block_info() {
  $blocks['facet_collection_search_block'] = array(
    'info' => t('Search block for collection')
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function facet_collection_search_block_block_view($delta = '') {
  if (user_access('search content')) {
    $block['subject'] = t('Search');
    $block['content'] = drupal_get_form('facet_collection_search_block_form');
    return $block;
  }
}

/**
 * Form callback for search block
 */
function facet_collection_search_block_form($form, &$form_state) {
  $search_query_string = arg(1);
  $default_value = '';
  if (!empty($search_query_string) && arg(0) == 'library') {
    $default_value = $search_query_string;
  }
  $form_id = $form_state['build_info']['form_id'];
  $form[$form_id] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#title_display' => 'invisible',
    '#size' => 15,
    '#default_value' => $default_value,
    '#attributes' => array('title' => t('Enter the terms you wish to search for.')),
  );

  $form['actions'] = array('#type' => 'actions');
  if (arg(0) == 'library') {
    $get_value = json_encode(array_diff_key($_GET, array(
      'q' => 1,
      'page' => 1,
      'solrsort' => 1,
      'retain-filters' => 1
    )));
  }
  else {
    $get_value = json_encode(array());
  }
  $form['basic']['get'] = array(
    '#type' => 'hidden',
    '#default_value' => $get_value,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#submit' => array('facet_collection_search_block_form_submit'),
    '#value' => t('Search')
  );
  if (arg(0) == 'library') {
    $clear_access = TRUE;
  }
  else {
    $clear_access = FALSE;
  }
  $form['clear'][] = array(
    '#type' => 'submit',
    '#submit' => array('facet_collection_search_block_form_remove_filter'),
    '#value' => t('Remove filter'),
    '#access' => $clear_access,
    '#attributes' => array(
      'class' => array('remove_filter'),
    ),
  );
  return $form;
}

/**
 * Submit callback for search block form
 */
function facet_collection_search_block_form_submit($form, &$form_state) {
  $form_id = $form['form_id']['#value'];
  if ($form_state['values'][$form_id] == '') {
    form_set_error('keys', t('Please enter some keywords.'));
  }
  $search_query = trim($form_state['values'][$form_id]);
  $get = json_decode($form_state['values']['get'], TRUE);
  //Check if we have filters. If not, then we should set filter by content type files, because it means that we go from another page
  if (!isset($get['f'])) {
    $get['f'][] = 'bundle:files';
  }
  if (!empty($search_query)) {
    $redirect_path = 'library/' . $search_query;
  }else{
    $redirect_path = 'library';
  }
  $form_state['redirect'] = array($redirect_path, array('query' => $get));
}

/**
 * Clear callback for search block form
 */
function facet_collection_search_block_form_remove_filter($form, &$form_state) {
  $get = json_decode($form_state['values']['get'], TRUE);
  $redirect_path = 'library';
  $form_state['redirect'] = array($redirect_path, array('query' => $get));
}