<?php

/**
 * Implements hook_menu().
 */
function library_background_menu() {
  $items = array();
  $items['admin/config/background'] = array(
    'title' => t('Variations background images'),
    'description' => t('This page is contain all settings for background images.'),
    'position' => 'left',
    'weight' => -5,
    'page callback' => 'library_background_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'library_background.admin.inc',
  );
  $items['admin/config/background/homepage-settings'] = array(
    'title' => t('Background images homepage configuration page'),
    'description' => t('This page is contain all settings for the homepage.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('library_background_homepage_bgs_form'),
    'access arguments' => array('administer site configuration'),
  );
//  $items['admin/config/background/pages-settings'] = array(
//    'title' => t('Background images others pages configuration page'),
//    'description' => t('This page is contain all settings for others pages.'),
//    'page callback' => 'drupal_get_form',
//    'page arguments' => array('library_background_pages_settings_form'),
//    'access arguments' => array('administer site configuration'),
//    'file' => 'library_background_pages.admin.inc',
//  );
  return $items;
}

/**
 * Implements hook_init().
 */
function library_background_init() {
  drupal_add_js(drupal_get_path('module', 'library_background') . '/library_background.js');
  drupal_add_css(drupal_get_path('module', 'library_background') . '/library_background.css');
}

/**
 * @file
 * Menu callbacks and helpers for admin part.
 */

/**
 * Provide a single block from the administration menu as a page.
 *
 * This function is often a destination for these blocks.
 * For example, 'admin/structure/types' needs to have a destination to be valid
 * in the Drupal menu system, but too much information there might be
 * hidden, so we supply the contents of the block.
 *
 * @return
 *   The output HTML.
 */
function library_background_menu_block_page() {
  $item = menu_get_item();
  if ($content = system_admin_menu_block($item)) {
    $output = theme('admin_block_content', array('content' => $content));
  }
  else {
    $output = t('You do not have any administrative items.');
  }
  return $output;
}

/**
 * Settings form for library background settings.
 */
function library_background_homepage_bgs_form() {
  $form = array();

  $form['library_background_homepage_css_repeat'] = array(
        '#type' => 'radios',
        '#title' => t('Repeat'),
        '#default_value' => variable_get('library_background_homepage_css_repeat') ? variable_get('library_background_homepage_css_repeat') : 'repeat',
        '#options' => array(
            'repeat' => t('Repeat'),
            'repeat-x' => t('Repeat Horizontally'),
            'repeat-y' => t('Repeat Vertically'),
            'no-repeat' => t('No Repeat')
        ),
        '#required' => TRUE,
    );

    $form['library_background_homepage_css_h_position'] = array(
        '#type' => 'radios',
        '#title' => t('Horizontal Position'),
        '#default_value' => variable_get('library_background_homepage_css_h_position') ? variable_get('library_background_homepage_css_h_position') : 'center',
        '#options' => array(
            'left' => t('Left'),
            'center' => t('Center'),
            'right' => t('Right'),
            'other' => t('Other')
        ),
        '#required' => TRUE,
    );

    $form['library_background_homepage_css_h_position_other'] = array(
        '#type' => 'textfield',
        '#default_value' => variable_get('library_background_homepage_css_h_position_other', ''),
        '#required' => TRUE,
        '#states' => array(
            'visible' => array(
                ':input[name="library_background_homepage_css_h_position"]' => array('value' => 'other'),
            ),
        ),
    );

    $form['library_background_homepage_css_v_position'] = array(
        '#type' => 'radios',
        '#title' => t('Vertical Position'),
        '#default_value' => variable_get('library_background_homepage_css_v_position') ? variable_get('library_background_homepage_css_v_position') : 'center',
        '#options' => array(
            'top' => t('Top'),
            'center' => t('Center'),
            'bottom' => t('Bottom'),
            'other' => t('Other')
        ),
        '#required' => TRUE,
    );

    $form['library_background_homepage_css_v_position_other'] = array(
        '#type' => 'textfield',
        '#default_value' => variable_get('library_background_homepage_css_v_position_other', ''),
        '#required' => TRUE,
        '#states' => array(
            'visible' => array(
                ':input[name="library_background_homepage_css_v_position"]' => array('value' => 'other'),
            ),
        ),
    );

    $form['library_background_homepage_css_attachment'] = array(
        '#type' => 'radios',
        '#title' => t('Attachment'),
        '#default_value' => variable_get('library_background_homepage_css_attachment') ? variable_get('library_background_homepage_css_attachment') : 'fixed',
        '#options' => array(
            'scroll' => t('Scroll'),
            'fixed' => t('Fixed'),
        ),
        '#required' => TRUE,
    );

    $form['library_background_homepage_css_important'] = array(
        '#type' => 'checkbox',
        '#title' => t('!important'),
        '#default_value' => variable_get('library_background_homepage_css_important') != FALSE ? variable_get('library_background_homepage_css_important') : '',
    );

    $form['library_background_homepage_uploaded_images'] = array(
        '#markup' => library_background_load_files(),
    );

    $form['library_background_homepage_deleted_image'] = array('#type' => 'hidden', '#value' => '');

    $form['library_background_homepage_image'] = array(
        '#type' => 'plupload',
        '#title' => t('Background image'),
        '#autosubmit' => FALSE,
        '#default_value' => variable_get('library_background_homepage_image', ''),
        '#upload_validators' => array(
            'file_validate_extensions' => array('jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp'),
        ),
    );

    $form['library_background_homepage_deleted_image'] = array(
        '#type' => 'textfield',
        '#default_value' => '',
        '#required' => FALSE,
        '#attributes' => array('class' => array('hide-me'))
    );

    // Callbacks.
    $form['actions']['#type'] = 'actions';
    $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save'),
        '#submit' => array(
          'library_background_homepage_uploaded_images_remove_callback',
          'library_background_homepage_bgs_form_submit')
    );

    if (!empty($_POST) && form_get_errors()) {
      drupal_set_message(t('The settings have not been saved because of the errors.'), 'error');
    }
    // By default, render the form using theme_system_settings_form().
    if (!isset($form['#theme'])) {
      $form['#theme'] = 'system_settings_form';
    }
    return $form;
}

/**
 * Callback for the submit of admin form for homepage fieldset.
 */
function library_background_homepage_bgs_form_submit($form, &$form_state) {
    $saved_files = array();
    $images = variable_get('library_background_homepage_images');
    if (!empty($images)) {
        $ids = library_background_check_files(explode(',', $images));
    } else {
        $ids = array();
    }
    if ($images = $form_state['values']['library_background_homepage_image']) {
        $scheme = variable_get('file_default_scheme', 'public') . '://';
        if (!is_dir('sites/default/files/hp/')) {
            drupal_mkdir('sites/default/files/hp/');
        }
        $scheme .= 'hp/';
        foreach ($images as $uploaded_file) {
            if ($uploaded_file['status'] == 'done') {
                $source = $uploaded_file['tmppath'];
                $destination = file_stream_wrapper_uri_normalize($scheme . $uploaded_file['name']);
                $destination = file_unmanaged_move($source, $destination, FILE_EXISTS_RENAME);
                $file = plupload_file_uri_to_object($destination);
                file_save($file);
                drupal_write_record('files', $file);
                if (file_exists('sites/default/files/hp/' . $file->name) == TRUE) {
                    $ids[] = $file->fid;
                    $saved_files[] = $file;
                }
            }
            else {
                form_set_error('pud', "Upload of {$uploaded_file['name']} failed");
            }
        }
        $fids = implode(',', $ids);
        variable_set('library_background_homepage_images', $fids);
        cache_clear_all();
    }
}


/**
 * Helping function for get random background image by id.
 */
function library_background_homepage_get_css() {
  $image = array();
  $image['url'] = library_background_homepage_get_file_random();
  $importand = variable_get('library_background_homepage_css_important');
  $image['css_repeat'] = variable_get('library_background_homepage_css_repeat');
  $css_hp = variable_get('library_background_homepage_css_h_position', '');
  $image['css_h_position'] = $css_hp == 'other'
    ? variable_get('library_background_homepage_css_h_position_other') . 'px '
    : $css_hp;
  $css_vp = variable_get('library_background_homepage_css_v_position');
  $image['css_v_position'] = $css_vp == 'other'
    ? variable_get('library_background_homepage_css_v_position_other') . 'px '
    : $css_vp;
  $image['css_attachment'] = variable_get('library_background_homepage_css_attachment');
  $image['important'] = isset($importand) && $importand != FALSE ? '!important' : '';
  return $image;
}

/**
 * Helping function for get random background image by id.
 */
function library_background_simple_get_css() {
  $image['url'] = library_background_simple_get_file_random();
  $importand = variable_get('library_background_simple_css_important');
  $image['css_repeat'] = variable_get('library_background_simple_css_repeat');
  $css_hp = variable_get('library_background_simple_css_h_position', '');
  $image['css_h_position'] = $css_hp == 'other'
    ? variable_get('library_background_simple_css_h_position_other') . 'px '
    : $css_hp;
  $css_vp = variable_get('library_background_simple_css_v_position');
  $image['css_v_position'] = $css_vp == 'other'
    ? variable_get('library_background_simple_css_v_position_other') . 'px '
    : $css_vp;
  $image['css_attachment'] = variable_get('library_background_simple_css_attachment');
  $image['important'] = isset($importand) && $importand != FALSE ? '!important' : '';
  return $image;
}

/**
 * Process variables for html.tpl.php.
 *
 * @see html.tpl.php
 */
function library_background_preprocess_html(&$variables) {
  global $theme;
  $options = array(
    'type' => 'inline',
    'group' => CSS_DEFAULT,
  );
  if ($variables['is_front'] == TRUE) {
    $file = library_background_homepage_get_css();
    $css = 'body' . ' { background: url("' . $file['url'] . '") !important;
    background-repeat: ' . $file['css_repeat'] . $file['important'] . ';
    background-position: ' . $file['css_h_position'] . ' ' . $file['css_v_position'] . $file['important'] . ';
    background-attachment: ' . $file['css_attachment'] . $file['important'] . '}';
    drupal_add_css($css, $options);
  } else {
    if ($theme == 'ellen_white_estate') {
      $file = library_background_simple_get_css();
      $css = 'body' . ' { background: url("' . $file['url'] . '") !important;
      background-repeat: ' . $file['css_repeat'] . $file['important'] . ';
      background-position: ' . $file['css_h_position'] . ' ' . $file['css_v_position'] . $file['important'] . ';
      background-attachment: ' . $file['css_attachment'] . $file['important'] . '}';
      drupal_add_css($css, $options);
    }
  }
}

/**
 * This is helper function that will build the thumb folder
 * for the background images.
 *
 * @param unknown_type $file
 */
function library_background_get_thumbnail($file) {
  $image = theme_image_style(
    array(
      'style_name' => 'thumbnail',
      'path' => $file->uri,
      'width' => '50px',
      'height' => '50px',
      'alt' => $file->filename,
      'title' => $file->filename,
      'attributes' => array(
        'class' => array('uploaded-image'),
        'id' => $file->fid,
      )
    )
  );
  return $image;
}

function library_background_load_files($homepage = TRUE) {
  $output = '';
  if ($homepage == TRUE) {
    $files = library_background_homepage_images_list(TRUE);
  } else {
    $files = library_background_simple_images_list(TRUE);
  }
  if (!empty($files) && is_array($files)) {
    foreach ($files as $uploaded_file) {
      $thumb = library_background_get_thumbnail($uploaded_file);
      $output .= $thumb;
    }
  }
  return $output;
}

/**
 * Callback for the submit of admin form for others pages fieldset.
 */
function library_background_simple_image_submit($form, $form_state) {
  $saved_files = array();
  $images = variable_get('library_background_simple_images');
  if (!empty($images)) {
    $ids = library_background_check_files(explode(',', $images), FALSE);
  } else {
    $ids = array();
  }
  if ($images = $form_state['values']['library_background_simple_image']) {
    $scheme = variable_get('file_default_scheme', 'public') . '://';
    if (!is_dir('sites/default/files/oth/')) {
      drupal_mkdir('sites/default/files/oth/');
    }
    $scheme .= 'oth/';
    foreach ($images as $uploaded_file) {
      if ($uploaded_file['status'] == 'done') {
        $source = $uploaded_file['tmppath'];
        $destination = file_stream_wrapper_uri_normalize($scheme . $uploaded_file['name']);
        $destination = file_unmanaged_move($source, $destination, FILE_EXISTS_RENAME);
        $file = plupload_file_uri_to_object($destination);
        file_save($file);
        drupal_write_record('files', $file);
        if (file_exists('sites/default/files/oth/' . $file->name) == TRUE) {
          $ids[] = $file->fid;
          $saved_files[] = $file;
        }
      }
      else {
        form_set_error('pud', "Upload of {$uploaded_file['name']} failed");
      }
    }
    $fids = implode(',', $ids);
    variable_set('library_background_simple_images', $fids);
    cache_clear_all();
  }
}

/**
 * Helper function for checking the files.
 */
function library_background_check_files($fids, $homepage = TRUE) {
  $images = array();
  $files = file_load_multiple($fids);
  $dir = $homepage == TRUE ? 'sites/default/files/lb/hp/' : 'sites/default/files/lb/oth/';
  foreach ($files as $file) {
    if (file_exists($dir . $file->filename) == TRUE) {
      $images[] = $file->fid;
    }
  }
  return $images;
}

/**
 * Helper function for create list of images.
 */
function library_background_homepage_images_list($full = FALSE) {
  $images_ids = variable_get('library_background_homepage_images');
  if (!empty($images_ids)) {
    $fids = explode(',', $images_ids);
    $files = file_load_multiple($fids);
    if (!empty($files)) {
      if ($full == FALSE) {
        foreach ($files as $file) {
          $images[] = file_create_url($file->uri);
        }
        cache_set('library_background_homepage_images', $images);
      return $images;
      } else {
        return $files;
      }
    }
  }
}

/**
 * Helper function for create list of images.
 */
function library_background_simple_images_list($full = FALSE) {
  $images_ids = variable_get('library_background_simple_images');
  if (!empty($images_ids)) {
    $fids = explode(',', $images_ids);
    $files = file_load_multiple($fids);
    if (!empty($files)) {
      if ($full == FALSE) {
        foreach ($files as $file) {
          $images[] = file_create_url($file->uri);
        }
        cache_set('library_background_simple_images', $images);
        return $images;
      } else {
        return $files;
      }
    }
  }
}

/**
 * Helper function for getting random image.
 */
function library_background_homepage_get_file_random() {
  $img = '';
  $bgs = cache_get('library_background_homepage_images');
  if (empty($bgs->data)) {
    $bgs = library_background_homepage_images_list();
    if (!empty($bgs)) {
      $id = array_rand($bgs);
      $img = $bgs[$id];
    }
  } else {
    if (!empty($bgs->data)) {
      $id = array_rand($bgs->data);
      $img = $bgs->data[$id];
    }
  }
  return $img;
}

/**
 * Helper function for getting random image.
 */
function library_background_simple_get_file_random() {
  $img = '';
  $bgs = cache_get('library_background_simple_images');
  if ($bgs == FALSE || empty($bgs->data)) {
    $bgs = library_background_simple_images_list();
    if (!empty($bgs)) {
      $id = array_rand($bgs);
      $img = $bgs[$id];
    }
  } else {
    if (!empty($bgs->data)) {
      $id = array_rand($bgs->data);
      $img = $bgs->data[$id];
    }
  }
  return $img;
}

/**
 * Callback for deleting images from list of uploaded images.
 */
function library_background_homepage_uploaded_images_remove_callback($form, &$form_state) {
  if ($need_deleted  = $form_state['input']['library_background_homepage_deleted_image']) {
    $fids = explode(', ', $need_deleted);
    $files = file_load_multiple($fids);
    foreach ($files as $file) {
      file_delete($file);
    }
  }
  if ($need_deleted  = $form_state['input']['library_background_simple_deleted_image']) {
    $fids = explode(', ', $need_deleted);
    $files = file_load_multiple($fids);
    foreach ($files as $file) {
      file_delete($file);
    }
  }
}

function library_background_form_alter($form, $form_state, $form_id) {
  kpr($form);
  if ($form_id == 'library_background_pages_settings_form') {

  }
}