<?php

/**
 * @file
 * Provides installation functions.
 */

/**
 * Implements hook_field_schema().
 */
function field_data_collector_field_schema($field) {
  $columns = array(
    'value' => array(
      'type' => 'blob',
      'size' => 'normal',
      'not null' => FALSE,
    ),
  );
  return array(
    'columns' => $columns,
  );
}

/**
 * Implements hook_uninstall().
 */
function field_data_collector_uninstall() {
  variable_del('field_data_collector_formatter_presets');
}