<?php

/**
 * Implements hook_uninstall().
 */
function filters_ui_datestamp_uninstall()
{
    $facet_filters_settings = drupal_json_decode(variable_get('facet_collection_filters_settings'));
    if (isset($facet_filters_settings['datestamp'])) {
        unset($facet_filters_settings['datestamp']);
        variable_set('facet_collection_filters_settings', drupal_json_encode($facet_filters_settings));
    }
}