<?php

/**
 * Implements hook_uninstall().
 */
function filters_ui_text_uninstall()
{
    $facet_filters_settings = drupal_json_decode(variable_get('facet_collection_filters_settings'));
    unset($facet_filters_settings['text']);
    unset($facet_filters_settings['text_long']);
    unset($facet_filters_settings['text_with_summary']);
    variable_set('facet_collection_filters_settings', drupal_json_encode($facet_filters_settings));
}