<?php

/**
 * Implements hook_uninstall().
 */
function facet_collection_ui_date_uninstall()
{
    $facet_filters_settings = drupal_json_decode(variable_get('facet_collection_filters_settings'));
    unset($facet_filters_settings['date']);
    unset($facet_filters_settings['datetime']);
    unset($facet_filters_settings['datestamp']);
    variable_set('facet_collection_filters_settings', drupal_json_encode($facet_filters_settings));
}