<?php

/**
 * Deleting information about field from information structure
 *
 * @param $field
 * @param $bundle
 * @param $facet_filters_settings
 * @param $filter
 */
function filters_ui_taxonomy_term_reference_delete_field($field, $bundle, &$facet_filters_settings, $filter) {
    if ($filter['state'] == 'visible') {
        $vocabulary_name = $field['settings']['allowed_values'][0]['vocabulary'];
        if (array_key_exists($bundle, $facet_filters_settings[$field['type']][$vocabulary_name])) {
            unset($facet_filters_settings[$field['type']][$vocabulary_name][$bundle]);
        }
    }
}

/**
 * Add information about field to information structure
 *
 * @param $field
 * @param $bundle
 * @param $facet_filters_settings
 * @param $filter
 */
function filters_ui_taxonomy_term_reference_add_field($field, $bundle, &$facet_filters_settings, $filter) {
    if ($filter['state'] == 'visible') {
        $vocabulary_name = $field['settings']['allowed_values'][0]['vocabulary'];
        if (!isset($facet_filters_settings[$field['type']][$vocabulary_name])) {
            $facet_filters_settings[$field['type']][$vocabulary_name] = array();
        }
        $facet_filters_settings[$field['type']][$vocabulary_name][$bundle] = array();
    }
}

/**
 * Return information by what current field would be filtered
 *
 * @param $field
 * @return string
 */
function filters_ui_taxonomy_term_reference_filter_by($field){
    $vocabulary = taxonomy_vocabulary_machine_name_load($field['settings']['allowed_values'][0]['vocabulary']);
    return 'Vocabulary ' . $vocabulary->name;
}