<?php

function files_filter_block_info() {
    $blocks = array();
    $blocks['files_filter_block'] = array(
        'info' => t('Block for filters'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function files_filter_block_view($delta = '') {
    if ($delta == 'files_filter_block') {

        $content = '<h2>Refine</h2>';
        $i = 0;
        foreach ($_GET as $key => $value) {
            $t_get = $_GET;
            $content .= '<div class="files_filter_refine_' . $i++ . '">';
             if (strpos($key, "field_files_doc_type_tid") !== false) {
                unset($t_get[$key]);
                $term_name = db_select('taxonomy_term_data', 't')
                                ->fields('t', array('name'))
                                ->condition('tid', $_GET[$key])
                                ->execute()
                                ->fetchObject()
                        ->name;
                $content .= l(t('Document type: ' . $term_name . '[X]'), "collection", array("query" => $t_get));
            }
            if (strpos($key, "field_files_category_tid") !== false) {
                unset($t_get[$key]);
                $term_name = db_select('taxonomy_term_data', 't')
                                ->fields('t', array('name'))
                                ->condition('tid', $_GET[$key])
                                ->execute()
                                ->fetchObject()
                        ->name;
                $content .= l(t('Category: ' . $term_name . '[X]'), "collection", array("query" => $t_get));
            }
            if (strpos($key, "field_files_collection_tid") !== false) {
                unset($t_get[$key]);
                $term_name = db_select('taxonomy_term_data', 't')
                                ->fields('t', array('name'))
                                ->condition('tid', $_GET[$key])
                                ->execute()
                                ->fetchObject()
                        ->name;
                $content .= l(t('Collection: ' . $term_name . '[X]'), "collection", array("query" => $t_get));
            }
            if (strpos($key, "field_files_groupe_tid") !== false) {
                unset($t_get[$key]);
                $term_name = db_select('taxonomy_term_data', 't')
                                ->fields('t', array('name'))
                                ->condition('tid', $_GET[$key])
                                ->execute()
                                ->fetchObject()
                        ->name;
                $content .= l(t('Groupe: ' . $term_name . '[X]'), "collection", array("query" => $t_get));
            }
            $content .= '</div>';
        }

        $result = db_query("
            SELECT taxonomy_term_data.name
                AS taxonomy_term_data_name, taxonomy_term_data.vid
                AS taxonomy_term_data_vid, taxonomy_term_data.tid
                AS tid, taxonomy_vocabulary.machine_name
                AS taxonomy_vocabulary_machine_name, COUNT(field_files_doc_type_taxonomy_term_data.nid)
                AS field_files_doc_type_taxonomy_term_data_nid
            FROM {taxonomy_term_data} taxonomy_term_data
            INNER JOIN {field_data_field_files_doc_type} field_data_field_files_doc_type ON taxonomy_term_data.tid = field_data_field_files_doc_type.field_files_doc_type_tid AND (field_data_field_files_doc_type.entity_type = 'node' AND field_data_field_files_doc_type.deleted = '0')
            INNER JOIN {node} field_files_doc_type_taxonomy_term_data ON field_data_field_files_doc_type.entity_id = field_files_doc_type_taxonomy_term_data.nid
            LEFT JOIN {taxonomy_vocabulary} taxonomy_vocabulary ON taxonomy_term_data.vid = taxonomy_vocabulary.vid
            WHERE (( (taxonomy_vocabulary.machine_name IN  ('library_voc_doc_type')) ))
            GROUP BY taxonomy_term_data_name, taxonomy_term_data_vid, tid, taxonomy_vocabulary_machine_name");

        $query = array();
        //var_dump($_GET);
        foreach ($_GET as $key => $value) {
            if (strpos($key, "field_files_doc_type_tid") === false)
                $query["{$key}"] = $value;
        }
        $content .= '<h2>Document type</h2>';
        while ($res = $result->fetchObject()) {
            $content .= '<div class="files_filter_term_' . $res->tid . '">';
            $tquery = $query;
            $tquery["field_files_doc_type_tid[]"] = $res->tid;
            $content .= l(t($res->taxonomy_term_data_name . '(' . $res->field_files_doc_type_taxonomy_term_data_nid . ')'), "collection", array("query" => $tquery));
            $content .= '</div>';
        }

        $result = db_query("
                SELECT taxonomy_term_data.name
                    AS taxonomy_term_data_name, taxonomy_term_data.vid
                    AS taxonomy_term_data_vid, taxonomy_term_data.tid
                    AS tid, taxonomy_vocabulary.machine_name
                    AS taxonomy_vocabulary_machine_name, COUNT(field_files_category_taxonomy_term_data.nid)
                    AS field_files_category_taxonomy_term_data_nid
                FROM {taxonomy_term_data} taxonomy_term_data
                INNER JOIN {field_data_field_files_category} field_data_field_files_category ON taxonomy_term_data.tid = field_data_field_files_category.field_files_category_tid AND (field_data_field_files_category.entity_type = 'node' AND field_data_field_files_category.deleted = '0')
                INNER JOIN {node} field_files_category_taxonomy_term_data ON field_data_field_files_category.entity_id = field_files_category_taxonomy_term_data.nid
                LEFT JOIN {taxonomy_vocabulary} taxonomy_vocabulary ON taxonomy_term_data.vid = taxonomy_vocabulary.vid
                WHERE (( (taxonomy_vocabulary.machine_name IN  ('library_voc_cat')) ))
                GROUP BY taxonomy_term_data_name, taxonomy_term_data_vid, tid, taxonomy_vocabulary_machine_name");

        $query = array();
        foreach ($_GET as $key => $value) {
            if (strpos($key, "field_files_category_tid") === false)
                $query["{$key}"] = $value;
        }
        $content .= '<h2>Category</h2>';
        while ($res = $result->fetchObject()) {
            $content .= '<div class="files_filter_term_' . $res->tid . '">';
            $tquery = $query;
            $tquery["field_files_category_tid[]"] = $res->tid;
            $content .= l(t($res->taxonomy_term_data_name . '(' . $res->field_files_category_taxonomy_term_data_nid . ')'), "collection", array("query" => $tquery));
            $content .= '</div>';
        }

        $result = db_query("
            SELECT taxonomy_term_data.name 
                AS taxonomy_term_data_name, taxonomy_term_data.vid 
                AS taxonomy_term_data_vid, taxonomy_term_data.tid 
                AS tid, taxonomy_vocabulary.machine_name 
                AS taxonomy_vocabulary_machine_name, COUNT(field_files_collection_taxonomy_term_data.nid) 
                AS field_files_collection_taxonomy_term_data_nid
            FROM {taxonomy_term_data} taxonomy_term_data
            LEFT JOIN {field_data_field_files_collection} field_data_field_files_collection ON taxonomy_term_data.tid = field_data_field_files_collection.field_files_collection_tid AND (field_data_field_files_collection.entity_type = 'node' AND field_data_field_files_collection.deleted = '0')
            LEFT JOIN {node} field_files_collection_taxonomy_term_data ON field_data_field_files_collection.entity_id = field_files_collection_taxonomy_term_data.nid
            LEFT JOIN {taxonomy_vocabulary} taxonomy_vocabulary ON taxonomy_term_data.vid = taxonomy_vocabulary.vid
            WHERE (( (taxonomy_vocabulary.machine_name IN  ('library_voc_collection')) ))
            GROUP BY taxonomy_term_data_name, taxonomy_term_data_vid, tid, taxonomy_vocabulary_machine_name");

        $query = array();
        foreach ($_GET as $key => $value) {
            if (strpos($key, "field_files_collection_tid") === false)
                $query["{$key}"] = $value;
        }
        $content .= '<h2>Collection</h2>';
        while ($res = $result->fetchObject()) {
            $content .= '<div class="files_filter_term_' . $res->tid . '">';
            $tquery = $query;
            $tquery["field_files_collection_tid[]"] = $res->tid;
            $content .= l(t($res->taxonomy_term_data_name . '(' . $res->field_files_collection_taxonomy_term_data_nid . ')'), "collection", array("query" => $tquery));
            $content .= '</div>';
        }

        $result = db_query("
            SELECT taxonomy_term_data.name 
                AS taxonomy_term_data_name, taxonomy_term_data.vid 
                AS taxonomy_term_data_vid, taxonomy_term_data.tid 
                AS tid, taxonomy_vocabulary.machine_name 
                AS taxonomy_vocabulary_machine_name, COUNT(field_files_groupe_taxonomy_term_data.nid) 
                AS field_files_groupe_taxonomy_term_data_nid
            FROM {taxonomy_term_data} taxonomy_term_data
            INNER JOIN {field_data_field_files_groupe} field_data_field_files_groupe ON taxonomy_term_data.tid = field_data_field_files_groupe.field_files_groupe_tid AND (field_data_field_files_groupe.entity_type = 'node' AND field_data_field_files_groupe.deleted = '0')
            INNER JOIN {node} field_files_groupe_taxonomy_term_data ON field_data_field_files_groupe.entity_id = field_files_groupe_taxonomy_term_data.nid
            LEFT JOIN {taxonomy_vocabulary} taxonomy_vocabulary ON taxonomy_term_data.vid = taxonomy_vocabulary.vid
            WHERE (( (taxonomy_vocabulary.machine_name IN  ('library_voc_groupe')) ))
            GROUP BY taxonomy_term_data_name, taxonomy_term_data_vid, tid, taxonomy_vocabulary_machine_name");
        
        $query = array();
        foreach ($_GET as $key => $value) {
            if (strpos($key, "field_files_groupe_tid") === false)
                $query["{$key}"] = $value;
        }
        $content .= '<h2>Groupe</h2>';
        while ($res = $result->fetchObject()) {
            $content .= '<div class="files_filter_term_' . $res->tid . '">';
            $tquery = $query;
            $tquery["field_files_groupe_tid[]"] = $res->tid;
            $content .= l(t($res->taxonomy_term_data_name . '(' . $res->field_files_groupe_taxonomy_term_data_nid . ')'), "collection", array("query" => $tquery));
            $content .= '</div>';
        }
        
        $block = array(
            'subject' => t(''),
            'content' => $content,
        );
        return $block;
    }
}
