<?php

function collection_slider_preprocess_page(&$variables)
{
    if (arg(0) == 'node'
        && is_numeric(arg(1))
        && (isset($_GET['collection']) && $_GET['collection'] == 'true')
        && isset($_GET['curr'])) {
        drupal_add_css(drupal_get_path('module', 'collection_slider') . '/css/collection-slider-buttons-style.css');
        drupal_add_js(drupal_get_path('module', 'collection_slider') . '/js/collection-slider-buttons.js');
        collection_slider_set_arrows_urls();
    }
}

function collection_slider_set_arrows_urls()
{

    $params = array();
    $params['q'] = 'entity_type:node';
    $params['defType'] = 'lucene';
    $params['spellcheck'] = FALSE;
    $params['start'] = ($_GET['curr'] > 0) ? $_GET['curr'] - 1 : $_GET['curr'];
    $params['rows'] = ($_GET['curr'] > 0) ? 3 : 2;
    $params['fl'] = 'entity_id';

    $query = apachesolr_drupal_query('apachesolr', $params);
    $searcher = $query->getSearcher();
    if (module_exists('facetapi')) {
        // Gets enabled facets, adds filter queries to $params.
        $adapter = facetapi_adapter_load($searcher);
        if ($adapter) {
            // Realm could be added but we want all the facets
            $adapter->addActiveFilters($query);
        }
    }
    $keys = $query->getParam('q');
    $response = $query->search($keys);

    $next_node_html = '';
    $previous_node_html = '';

    $options = array('query' => array());
    $options['query'] ['collection'] = 'true';
    if (isset($_GET['f'])) {
        $f = $_GET['f'];
        $options['query'] ['f'] = $f;
    }

    if ($_GET['curr'] > 0) {
        $options['query']['curr'] = $_GET['curr'] - 1;
        $options['attributes']['class'] = array('collection-slider-button-icon-swapleft', ' active');
        $previous_node_id = $response->response->docs[0]->entity_id;
        $previous_node_url = 'node/' . $previous_node_id . '';
        $previous_node_html = l('', $previous_node_url, $options);
    }

    if ($_GET['curr'] + 1 < $response->response->numFound) {
        $options['query']['curr'] = $_GET['curr'] + 1;
        $options['attributes']['class'] = array('collection-slider-button-icon-swapright', ' active');
        $next_node_id = $response->response->docs[count($response->response->docs) - 1]->entity_id;
        $next_node_url = 'node/' . $next_node_id . '';
        $next_node_html = l('', $next_node_url, $options);
    }

    drupal_add_js(array('collection_arrows' => array('next_node_html' => $next_node_html, 'previous_node_html' => $previous_node_html)), 'setting');

    unset($options['query']['collection']);
    unset($options['attributes']);
    $back_to_collection_html = l('Back to Collection', 'collection', $options);

    drupal_add_js(array('collection_arrows' => array('back_to_collection_html' => $back_to_collection_html)), 'setting');
}