<?php

/**
 * Implements hook_filters_ui_field_type_info().
 */
function filters_ui_date_filters_ui_field_type_info()
{
    return array('date', 'datetime', 'datestamp');
}

/**
 * Implements hook_filters_ui_delete_field().
 */
function filters_ui_date_filters_ui_delete_field($field, $bundle, &$facet_filters_settings, $filter)
{
    if ($filter['state'] == 'visible') {
        if (array_key_exists($bundle, $facet_filters_settings[$field['type']])) {
            unset($facet_filters_settings[$field['type']][$bundle]);
        }
    }
}

/**
 * Implements hook_filters_ui_add_field().
 */
function filters_ui_date_filters_ui_add_field($field, $bundle, &$facet_filters_settings, $filter)
{
    if ($filter['state'] == 'visible') {
        if (!isset($facet_filters_settings[$field['type']])) {
            $facet_filters_settings[$field['type']] = array();
        }
        $facet_filters_settings[$field['type']][$bundle] = array();
    }
}

/**
 * Implements hook_filters_ui_filter_by().
 */
function filters_ui_date_filters_ui_filter_by($field)
{
    return 'Date';
}