<?php

function collection_layout_block_info() {
    $blocks = array();
    $blocks['files_filter_block'] = array(
        'info' => t('Block for filters'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}

function collection_layout_menu() {
    $items['collection'] = array(
        'title' => 'Collection',
        'access callback' => TRUE,
        'page callback' => 'collection_layout_page_callback',
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function get_filters_list() {
    return array('document_type', 'collection', 'category', 'group', 'date', 'creator');
}

function is_filter($arg) {
    return in_array($arg, get_filters_list());
}

function set_filter_value($fid, $val) {
    $_SESSION['collection_layout'][$fid][] = $val;
}

function add_filter_value($fid, $val) {
    if ($fid == 'date') {
        if (isset($val['year'])){
            if (isset($_SESSION['collection_layout'][$fid]['year'])){
                if ($_SESSION['collection_layout'][$fid]['year'] == $val['year'])
                    unset($_SESSION['collection_layout'][$fid]['year']);
                else
                    $_SESSION['collection_layout'][$fid]['year'] = $val['year'];
            }else
                $_SESSION['collection_layout'][$fid]['year'] = $val['year'];
        }
        if (isset($val['min']) && isset($val['max'])) {
            $_SESSION['collection_layout'][$fid]['min'] = $val['min'];
            $_SESSION['collection_layout'][$fid]['max'] = $val['max'];
        }
        return;
    }
    if (isset($_SESSION['collection_layout'][$fid]))
        if (!in_array($val, $_SESSION['collection_layout'][$fid])) {
            set_filter_value($fid, $val);
        } else
            remove_filter_value($fid, $val);
    else
        set_filter_value($fid, $val);
}

function remove_filter_value($fid, $val) {
    if (in_array($val, $_SESSION['collection_layout'][$fid]))
        foreach ($_SESSION['collection_layout'][$fid] as $key => $value) {
            if ($val == $value)
                unset($_SESSION['collection_layout'][$fid][$key]);
        }
}

function get_filter_value($fid) {
    if (is_filter($fid))
        if (isset($_SESSION['collection_layout'][$fid]))
            return $_SESSION['collection_layout'][$fid];
        else
            return false;
}

function get_filter_list() {
    $list = array();
    if (isset($_SESSION['collection_layout']))
        foreach ($_SESSION['collection_layout'] as $key => $value) {
            if (is_filter($key))
                $list[$key] = $value;
        }
    return empty($list) ? false : $list;
}

function get_filter_human_name($fid) {
    switch ($fid) {
        case 'document_type' :
            return 'Document type';
        case 'collection' :
            return 'Collection';
        case 'category' :
            return 'Category';
        case 'group' :
            return 'Groupe';
        case 'data' :
            return '';
        default :
            return false;
    }
}

function get_term_name($tid) {
    return $term_name = db_select('taxonomy_term_data', 't')
                    ->fields('t', array('name'))
                    ->condition('tid', $tid)
                    ->execute()
                    ->fetchObject()
            ->name;
}

function collection_layout_page_callback() {
    if (!isset($_SESSION['collection_layout']['date']['min']))
        $_SESSION['collection_layout']['date']['min'] = 1000;
    if (!isset($_SESSION['collection_layout']['date']['max']))
        $_SESSION['collection_layout']['date']['max'] = 2050;
    foreach ($_GET as $key => $value) {
        if (is_filter($key))
            add_filter_value($key, $value);
    }
    $doc_type = get_filter_value('document_type');
    $doc_type_filter_string = $doc_type ? implode('+', $doc_type) : 'all';

    $collection = get_filter_value('collection');
    $collection_filter_string = $collection ? implode('+', $collection) : 'all';

    $category = get_filter_value('category');
    $category_filter_string = $category ? implode('+', $category) : 'all';

    $group = get_filter_value('group');
    $group_filter_string = $group ? implode('+', $group) : 'all';

    $date = get_filter_value('date');
    $date_range_filter_string = isset($date['min']) ? "{$date['min']}--{$date['max']}" : 'all';
    $date_filter_string = isset($date['year']) ? $date['year'] : 'all';
    $result = views_embed_view('collection_view', 'page', $date_range_filter_string, $doc_type_filter_string, $category_filter_string, $collection_filter_string, $group_filter_string, $date_filter_string);

    return $result;
}

function collection_layout_block_view() {
    if (!isset($_SESSION['collection_layout']['date']['min']))
        $_SESSION['collection_layout']['date']['min'] = 1000;
    if (!isset($_SESSION['collection_layout']['date']['max']))
        $_SESSION['collection_layout']['date']['max'] = 2050;
    drupal_add_library('system', 'ui.slider');
    drupal_add_js(array('collection_layout' => array(
            'date_min' => $_SESSION['collection_layout']['date']['min'],
            'date_max' => $_SESSION['collection_layout']['date']['max'],
            )), 'setting');
    $result = '<h2>Publication date</h2>';
    $result .= '<div id="slider-date-range"></div>';
    $filter_list = get_filter_list();
    if ($filter_list)
        $result .= '<h2>Refine</h2>';
    foreach ($filter_list as $fid => $val) {
        if ($fid != 'date')
            if (is_array($val))
                foreach ($val as $tid) {
                    $result .= '<div class="' . $fid . '_' . $tid . '">';
                    $result .= l(get_filter_human_name($fid) . ': ' . get_term_name($tid) . '[X]', 'collection', array(
                        'query' => array(
                            $fid => $tid
                            )));
                    $result .= '</div>';
                } else {
                $result .= '<div class="' . $fid . '_' . $val . '">';
                $result .= l(get_filter_human_name($fid) . ': ' . get_term_name($val) . '[X]', 'collection', array(
                    'query' => array(
                        $fid => $val
                        )));
                $result .= '</div>';
            } else
        if (isset($val['year'])) {
            $result .= '<div class="' . $fid . '_' . $val['year'] . '">';
            $result .= l($val['year'] . '[X]', 'collection', array(
                'query' => array(
                    'date[year]' => $val['year']
                    )));
            $result .= '</div>';
        }
    }

    $date = get_filter_value('date');
    $date_range_filter_string = isset($date['min']) ? "{$date['min']}--{$date['max']}" : 'all';
    $date_filter_string = isset($date['year']) ? $date['year'] : 'all';
    $doc_type = get_filter_value('document_type');
    $doc_type_filter_string = $doc_type ? implode('+', $doc_type) : 'all';
    $category = get_filter_value('category');
    $category_filter_string = $category ? implode('+', $category) : 'all';
    $collection = get_filter_value('collection');
    $collection_filter_string = $collection ? implode('+', $collection) : 'all';
    $group = get_filter_value('group');
    $group_filter_string = $group ? implode('+', $group) : 'all';

    $result .= '<h2>Document type</h2>';
    $result .= views_embed_view('document_type_views', 'page', $date_range_filter_string, $category_filter_string, $collection_filter_string, $group_filter_string, $date_filter_string);

    $result .= '<h2>Category</h2>';
    $result .= views_embed_view('category_view', 'page', $date_range_filter_string, $doc_type_filter_string, $collection_filter_string, $group_filter_string, $date_filter_string);

    $result .= '<h2>Collection</h2>';
    $result .= views_embed_view('collection_view_taxonomy', 'page', $date_range_filter_string, $doc_type_filter_string, $category_filter_string, $group_filter_string, $date_filter_string);

    $result .= '<h2>Groupe</h2>';
    $result .= views_embed_view('groupe_view', 'page', $date_range_filter_string, $doc_type_filter_string, $category_filter_string, $collection_filter_string, $date_filter_string);

    $result .= '<h2>Publication date</h2>';
    $result .= views_embed_view('collection_view', 'block_1', $date_range_filter_string, $doc_type_filter_string, $category_filter_string, $collection_filter_string, $group_filter_string);

    $block = array(
        'subject' => t(''),
        'content' => $result,
    );
    return $block;
}

function collection_layout_field_formatter_info() {
    return array(
        'collection_layout_date_link' => array(
            'label' => t('Collection Layout Date Link'),
            'field types' => array('date', 'datestamp', 'datetime'),
        ),
        'colletion_layout_title_link' => array(
            'label' => t('Collection Layout Title Link'),
            'field types' => array('text'),
        ),
    );
}

/**
 * Implements hook_field_formatter_view().
 */
function collection_layout_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
    $element = array();
    switch ($display['type']) {
        case 'collection_layout_date_link':
            foreach ($items as $delta => $item) {
                $year = explode('-', $item['value']);
                $year = $year[0];
                $element[$delta] = array(
                    '#type' => 'markup',
                    '#markup' => l($year, 'collection', array(
                        'query' => array(
                            'date[year]' => $year
                        )
                    ))
                );
            }
            break;
        case 'colletion_layout_title_link' :
            foreach ($items as $delta => $item) {
                /* var_dump($entity);
                  exit; */
            }
            break;
    }
    return $element;
}

function collection_layout_views_api() {
    return array(
        'api' => 3,
    );
}

function collection_layout_views_data_alter(&$data) {
    $data['taxonomy_term_data']['name']['field'] = array(
        'handler' => 'collection_layout_handler_field_taxonomy',
        'click sortable' => TRUE,
    );
}