<?php

/**
 * Implements hook_menu()
 */
function library_import_menu() {
  $items['libimport'] = array(
      'title' => t('Import'),
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'library_import_page',
      'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Page callback for import page
 */
function library_import_page() {
  return drupal_get_form('library_import_form');
}

function library_import_form($form, &$form_state) {
  $form['submit'] = array(
      '#type' => 'submit',
      '#submit' => array('library_import_submit'),
      '#value' => t('Import')
  );
  return $form;
}

/**
 * Submiter for import
 */
function library_import_submit() {
  $other_database = array(
      'database' => 'adventists',
      'username' => 'admin', // assuming this is necessary
      'password' => '1234', // assuming this is necessary
      'host' => 'localhost', // assumes localhost
      'driver' => 'mysql', // replace with your database driver
  );
  Database::addConnectionInfo('ImportDatabaseKey', 'default', $other_database);
   $query = Database::getConnection('default', 'ImportDatabaseKey')
            ->select('adv_location_geocoding', 'l');
  $query->condition('l.loc_id', 1);
  $query->fields('l', array('data'));
//    $query->join('egw_linker2info', 'l2i', 'l2i.linker_id = l.linker_entry_id');
//    $query->join('egw_linker', 'l2', 'l2.linker_entry_id = l.linker_entry_id  AND l2.tb_name != l.tb_name');
//    $query->join('adv_date_time', 'dt', 'dt.ID = l.tb_id');
//    $query->addField('l', 'tb_name');
//    $query->addField('l2', 'linker_entry_id');
//    $query->addField('dt', 'ID');
//    $query->condition('l2i.linkerinfo_id', 18, '=');
//    $query->condition('l.tb_name', 'adv_location', '=');
//    $query->condition('l2.tb_name', 'adv_people', '=');
  //$query->condition('l.tb_name', 'adv_events', '=');
    //$query->isNotNull('dt.end_year');
   //$query->groupBy('l.tb_name');
//    $query->range(0, 20);
    $result = $query->execute();

    //$query->groupBy('l.file_extension');*$query = Database::getConnection('default', 'ImportDatabaseKey')

  while ($row = $result->fetchAssoc()) {
    $data = drupal_json_decode($row['data']);
         dpm($data);
    }
  /*$node = node_load(12503);
  dpm($node);*/
}